name: Rolling Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Generate release
      run: dotnet publish --no-build -c Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: NTypeWriterCLI-Rolling-Release
        path: NTypeWriterCli/bin/Release/netcoreapp3.1/publish
